import mongoose from 'mongoose';

const SiniestroSchema = new mongoose.Schema({
  nmro_ajste: String,
  codiRespnsble: { type: String, ref: 'Responsable' },
  codi_asgrdra: String,
  nmro_sinstro: String,
  cod_workflow: String,
  func_asgrdra: { type: String, ref: 'FuncionarioAseguradora' },
  fcha_asgncion: Date,
  asgr_benfcro: String,
  tipo_ducumento: String,
  num_documento: String,
  tipo_poliza: String,
  nmro_polza: String,
  ampr_afctdo: String,
  fcha_sinstro: Date,
  desc_sinstro: String,
  ciudad_siniestro: String,
  fcha_inspccion: Date,
  codi_estdo: String,
  fcha_cont_ini: Date,
  obse_cont_ini: String,
  anex_cont_ini: String,
  obse_inspccion: String,
  fcha_soli_docu: Date,
  anex_acta_inspccion: String,
  anex_sol_doc: String,
  obse_soli_docu: String,
  fcha_info_prelm: Date,
  obse_info_prelm: String,
  anxo_inf_prelim: String,
  fcha_info_fnal: Date,
  obse_info_fnal: String,
  anxo_info_fnal: String,
  fcha_repo_acti: Date,
  obse_repo_acti: String,
  anxo_repo_acti: String,
  fcha_ult_segui: Date,
  fcha_act_segui: Date,
  dias_transcrrdo: Number,
  obse_segmnto: String,
  vlor_resrva: Number,
  vlor_reclmo: Number,
  monto_indmzar: Number,
  nomb_intermediario: String,
  fcha_finqto_indem: Date,
  nmro_factra: String,
  vlor_servcios: Number,
  vlor_gastos: Number,
  total: Number,
  total_general: Number,
  total_pagado: Number,
  fcha_factra: Date,
  anxo_factra: String,
  anxo_honorarios: String,
  anxo_honorariosdefinit: String,
  anxo_autorizacion: String,
  fcha_ult_revi: Date,
  obse_comprmsi: String,
  iva: Number,
  reteiva: Number,
  retefuente: Number,
  reteica: Number,
  porc_iva: Number,
  porc_reteiva: Number,
  porc_retefuente: Number,
  porc_reteica: Number
}, { collection: 'gsk3cAppsiniestro' });

const Siniestro = mongoose.model('Siniestro', SiniestroSchema, 'gsk3cAppsiniestro');
export default Siniestro;
