// models/Complex.js
import mongoose from 'mongoose';

const ComplexSchema = new mongoose.Schema({
  // Campos principales según la base de datos real
  nmroAjste: { type: String, unique: true },
  codWorkflow: String,
  nmroSinstro: String,
  nombIntermediario: String,
  codiAsgrdra: String,
  funcAsgrdra: String,
  codiRespnsble: String,
  asgrBenfcro: String,
  tipoDucumento: String,
  numDocumento: String,
  tipoPoliza: String,
  nmroPolza: String,
  amprAfctdo: String,
  fchaSinstro: Date,
  descSinstro: String,
  ciudadSiniestro: String,
  fchaInspccion: Date,
  codiEstdo: String,
  fchaContIni: Date,
  obseContIni: String,
  anexContIni: String,
  obseInspccion: String,
  fchaSoliDocu: Date,
  anexActaInspccion: String,
  anexSolDoc: String,
  obseSoliDocu: String,
  fchaInfoPrelm: Date,
  obseInfoPrelm: String,
  anxoInfPrelim: String,
  fchaInfoFnal: Date,
  obseInfoFnal: String,
  anxoInfoFnal: String,
  fchaRepoActi: Date,
  obseRepoActi: String,
  anxoRepoActi: String,
  fchaUltSegui: Date,
  fchaActSegui: Date,
  diasTranscrrdo: Number,
  obseSegmnto: String,
  vlorResrva: Number,
  vlorReclmo: Number,
  montoIndmzar: Number,
  fchaFinqtoIndem: Date,
  nmroFactra: String,
  vlorServcios: Number,
  vlorGastos: Number,
  total: Number,
  iva: Number,
  reteiva: Number,
  retefuente: Number,
  reteica: Number,
  totalGeneral: Number,
  totalPagado: Number,
  fchaFactra: Date,
  anxoFactra: String,
  anxoHonorarios: String,
  anxoHonorariosdefinit: String,
  anxoAutorizacion: String,
  fchaUltRevi: Date,
  obseComprmsi: String,
  porcIva: Number,
  porcReteiva: Number,
  porcRetefuente: Number,
  porcReteica: Number,
  fchaAsgncion: Date,
  historialDocs: [
    {
      tipo: String,
      nombre: String,
      fecha: String,
      comentario: String
    }
  ],
}, { 
  collection: 'gsk3cAppsiniestro',
  // Usar la conexión principal de MongoDB
  connection: mongoose.connection
});

export default mongoose.model('Complex', ComplexSchema);
