// models/Complex.js
import mongoose from 'mongoose';

const ComplexSchema = new mongoose.Schema({
  numero_ajuste: { type: String, unique: true },
  codigo_workflow: String,
  numero_siniestro: String,
  intermediario: String,
  aseguradora: String,
  funcionario_aseguradora: String,
  responsable: String,
  asegurado: String,
  tipo_documento: String,
  numero_documento: String,
  fecha_siniestro: Date,
  ciudad_siniestro: String,
  descripcion_siniestro: String,
  estado: String,
  tipo_poliza: String,
  causa_siniestro: String,
  valor_reserva: Number,
  valor_reclamo: Number,
  monto_indemnizar: Number,
  fecha_contacto_inicial: Date,
  observaciones_contacto_inicial: String,
  adjuntos_contacto_inicial: String,
  fecha_inspeccion: Date,
  observacion_inspeccion: String,
  adjunto_acta_inspeccion: String,
  fecha_solicitud_documentos: Date,
  observacion_solicitud_documento: String,
  adjunto_solicitud_documento: String,
  fecha_informe_preliminar: Date,
  adjunto_informe_preliminar: String,
  observacion_informe_preliminar: String,
  fecha_informe_final: Date,
  adjunto_informe_final: String,
  observacion_informe_final: String,
  fecha_ultimo_documento: Date,
  adjunto_entrega_ultimo_documento: String,
  numero_factura: Number,
  valor_servicio: Number,
  valor_gastos: Number,
  iva: Number,
  reteiva: Number,
  retefuente: Number,
  reteica: Number,
  total_base: Number,
  total_factura: Number,
  total_pagado: Number,
  fecha_factura: Date,
  fecha_ultima_revision: Date,
  observacion_compromisos: String,
  adjunto_factura: String,
  fecha_ultimo_seguimiento: Date,
  observacion_seguimiento_pendientes: String,
  adjunto_seguimientos_pendientes: String,
  numero_poliza: String,
  fecha_asignacion: Date,
  creado_en: { type: Date, default: Date.now },
  historialDocs: [
    {
      tipo: String,
      nombre: String,
      fecha: String,
      comentario: String
    }
  ],
}, { collection: 'gsk3cAppsiniestro' });

export default mongoose.model('Complex', ComplexSchema);
